name: CI

on:
    push:
        branches: [main]

    pull_request:
        branches: [main]

jobs:
    build:
        strategy:
            matrix:
                os: [macos-latest, ubuntu-latest, windows-latest]
                node-version: [16.10.x, 17.x, 18.x]

        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependencies
              run: npm ci

            - name: Build
              run: npm run compile

            - name: Run tests
              uses: GabrielBB/xvfb-action@v1.0
              with:
                  run: npm test
